[build]
command = "npx next build"
publish = "out"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "9"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200